<a href="https://colab.research.google.com/github/sammanfatima/Her-ML-Journey/blob/main/Data_Inconsistencies.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Inconsistencies

1. Incocnistent format
* for example
* DD-MM-YYY, YYYY-MM-DD, DD/MM/YYYY
* Find out which format is important for you

2. Inconsistent Naming Conventions
* Data collected for countries sometimes it is written as USA, United States of America... you have to make these in one consistent form

3. Typographical errors
* Mistakes in data entries

4. Duplication
* one rows show again

5. contradictory data

In [1]:
import pandas as pd

In [2]:
df = {
    'date': ['2021-12-01', '01-12-2022', '2022/12/01', '12-01-2021'],
    'country': ['USA', 'U.S.A.', 'America', 'United States'],
    'name': ['John Doe', 'Jonh Doe', 'Jane Doe', 'Jane Doe'],
    'sales_2020': [100, 200, None, 200],
    'sales_2021': [None, 150, 300, 150]
}
# make pandas dataframes
df = pd.DataFrame(df)

In [3]:
df.head()

         date        country      name  sales_2020  sales_2021
0  2021-12-01            USA  John Doe       100.0         NaN
1  01-12-2022         U.S.A.  Jonh Doe       200.0       150.0
2  2022/12/01        America  Jane Doe         NaN       300.0
3  12-01-2021  United States  Jane Doe       200.0       150.0

# Standardizing date format

* Convert the date col into a proper date format
* df['date'] → selects the date column
* pd.to_datetime() → converts values into date format
* errors='coerce' → If a value is not a valid date, replace it with a missing value instead of showing an error.

In [4]:
df['date'] = pd.to_datetime(df['date'], errors='coerce')
df.head()

        date        country      name  sales_2020  sales_2021
0 2021-12-01            USA  John Doe       100.0         NaN
1        NaT         U.S.A.  Jonh Doe       200.0       150.0
2        NaT        America  Jane Doe         NaN       300.0
3        NaT  United States  Jane Doe       200.0       150.0

* It changes the date into specific format: Year-Month-Day

In [5]:
df['date'] = pd.to_datetime(df['date'], errors='coerce')
df['date'] = df['date'].dt.strftime('%Y-%m-%d')
df.head()

         date        country      name  sales_2020  sales_2021
0  2021-12-01            USA  John Doe       100.0         NaN
1         NaN         U.S.A.  Jonh Doe       200.0       150.0
2         NaN        America  Jane Doe         NaN       300.0
3         NaN  United States  Jane Doe       200.0       150.0

# Replace a specific value

In [6]:
df.head()

         date        country      name  sales_2020  sales_2021
0  2021-12-01            USA  John Doe       100.0         NaN
1         NaN         U.S.A.  Jonh Doe       200.0       150.0
2         NaN        America  Jane Doe         NaN       300.0
3         NaN  United States  Jane Doe       200.0       150.0

In [7]:
df.loc[3, 'date'] = '2022-12-08'

In [8]:
df.head()

         date        country      name  sales_2020  sales_2021
0  2021-12-01            USA  John Doe       100.0         NaN
1         NaN         U.S.A.  Jonh Doe       200.0       150.0
2         NaN        America  Jane Doe         NaN       300.0
3  2022-12-08  United States  Jane Doe       200.0       150.0

# Replace all missing date with same date

In [9]:
df['date'] = df['date'].fillna('2002-03-08')

In [10]:
df.head()

         date        country      name  sales_2020  sales_2021
0  2021-12-01            USA  John Doe       100.0         NaN
1  2002-03-08         U.S.A.  Jonh Doe       200.0       150.0
2  2002-03-08        America  Jane Doe         NaN       300.0
3  2022-12-08  United States  Jane Doe       200.0       150.0

# Make all country names follow the same format

In [11]:
country_mapping ={'USA': 'United States','U.S.A.': 'United States', 'America': 'United States'}
df['country']= df['country'].replace(country_mapping)
df.head()

         date        country      name  sales_2020  sales_2021
0  2021-12-01  United States  John Doe       100.0         NaN
1  2002-03-08  United States  Jonh Doe       200.0       150.0
2  2002-03-08  United States  Jane Doe         NaN       300.0
3  2022-12-08  United States  Jane Doe       200.0       150.0

# Correct the typographical mistakes in name

In [12]:
df['name'] = df['name'].replace({'Jonh Doe': 'John Doe'})
df.head()

         date        country      name  sales_2020  sales_2021
0  2021-12-01  United States  John Doe       100.0         NaN
1  2002-03-08  United States  John Doe       200.0       150.0
2  2002-03-08  United States  Jane Doe         NaN       300.0
3  2022-12-08  United States  Jane Doe       200.0       150.0

In [13]:
df.loc[2, 'name'] ='Sara'
df.head()

         date        country      name  sales_2020  sales_2021
0  2021-12-01  United States  John Doe       100.0         NaN
1  2002-03-08  United States  John Doe       200.0       150.0
2  2002-03-08  United States      Sara         NaN       300.0
3  2022-12-08  United States  Jane Doe       200.0       150.0

# Remove duplicates

In [14]:
df = df.drop_duplicates(subset="name")
df.head()

         date        country      name  sales_2020  sales_2021
0  2021-12-01  United States  John Doe       100.0         NaN
2  2002-03-08  United States      Sara         NaN       300.0
3  2022-12-08  United States  Jane Doe       200.0       150.0

In [30]:
df = {
    'date': ['2021-12-01', '01-12-2022', '2022/12/01', '12-01-2021'],
    'country': ['USA', 'U.S.A.', 'America', 'United States'],
    'name': ['Aammar', 'Amar', 'Hazma', 'Hamza'],
    'sales_2020': [100, 200, None, 200],
    'sales_2021': [None, 150, 300, 150]
}
# make pandas dataframes
df = pd.DataFrame(df)

In [31]:
df.head()

         date        country    name  sales_2020  sales_2021
0  2021-12-01            USA  Aammar       100.0         NaN
1  01-12-2022         U.S.A.    Amar       200.0       150.0
2  2022/12/01        America   Hazma         NaN       300.0
3  12-01-2021  United States   Hamza       200.0       150.0

In [32]:
df['name'] = df['name'].replace({'Amar': 'Aammar', 'Hazma': 'Hamza'})

In [33]:
df.head()

         date        country    name  sales_2020  sales_2021
0  2021-12-01            USA  Aammar       100.0         NaN
1  01-12-2022         U.S.A.  Aammar       200.0       150.0
2  2022/12/01        America   Hamza         NaN       300.0
3  12-01-2021  United States   Hamza       200.0       150.0

In [35]:
df['country']= df['country'].replace({'U.S.A.': 'United Staes', 'USA':'United States', 'America':'United States'})

In [34]:
df.head()

         date        country    name  sales_2020  sales_2021
0  2021-12-01            USA  Aammar       100.0         NaN
1  01-12-2022         U.S.A.  Aammar       200.0       150.0
2  2022/12/01        America   Hamza         NaN       300.0
3  12-01-2021  United States   Hamza       200.0       150.0

In [36]:
df = df.drop_duplicates(subset="name")
df.head()

         date        country    name  sales_2020  sales_2021
0  2021-12-01  United States  Aammar       100.0         NaN
2  2022/12/01  United States   Hamza         NaN       300.0

# Resolving Contradictory Data

In [38]:
df = df.drop(df[df['sales_2021'] <=df['sales_2020']].index)
df.head()

         date        country    name  sales_2020  sales_2021
0  2021-12-01  United States  Aammar       100.0         NaN
2  2022/12/01  United States   Hamza         NaN       300.0