<a href="https://colab.research.google.com/github/sammanfatima/Her-ML-Journey/blob/main/Data_Merging.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Merging

In [2]:
import pandas as pd

# Dataset 1:

In [5]:
data1 ={
    'id' : [1, 2, 3],
    'name': ['Ahmed', 'Fatima', 'Ali'],
    'age': [28, 32, 24]
}
df1 = pd.DataFrame(data1)
df1.head()

   id    name  age
0   1   Ahmed   28
1   2  Fatima   32
2   3     Ali   24

# Dataset 2:

In [7]:
data2 = {
    'id': [1, 2, 3],
    'city':['Karachi', 'Lahore', 'Islamabad'],
    'occupation': ['Engineer', 'Teacher', 'Developer']
}
df2 = pd.DataFrame(data2)
df2.head()

   id       city occupation
0   1    Karachi   Engineer
1   2     Lahore    Teacher
2   3  Islamabad  Developer

# Merging dataframes on 'id'

* pd.merge() is used to combine two dataframes together based on a common column

In [8]:
merge_df = pd.merge(df1, df2, on='id', how='inner')
merge_df.head()

   id    name  age       city occupation
0   1   Ahmed   28    Karachi   Engineer
1   2  Fatima   32     Lahore    Teacher
2   3     Ali   24  Islamabad  Developer