<a href="https://colab.research.google.com/github/sammanfatima/Her-ML-Journey/blob/main/Outliers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Outliers

In [1]:
import pandas as pd
import numpy as np

# Create the data

In [3]:
df = pd.DataFrame({'Age': [20, 21, 22, 23, 24, 25, 26,27, 28, 29, 30, 50]})
df

    Age
0    20
1    21
2    22
3    23
4    24
5    25
6    26
7    27
8    28
9    29
10   30
11   50

# Calculate the mean and standard deviation

In [5]:
mean = np.mean(df['Age'])
std = np.std(df['Age'])

# Calculate the Z-Score

* Z-score tells us how far a value is from the mean.

In [9]:
df['Z-Score'] = (df['Age'] - mean) / std
df

    Age   Z-Score
0    20 -0.938954
1    21 -0.806396
2    22 -0.673838
3    23 -0.541280
4    24 -0.408721
5    25 -0.276163
6    26 -0.143605
7    27 -0.011047
8    28  0.121512
9    29  0.254070
10   30  0.386628
11   50  3.037793

# Print outliers

In [11]:
print(f'Here are outliers based on the zscore threshold, 3:\n {df[df['Z-Score'] > 3]}')

Here are outliers based on the zscore threshold, 3:
     Age   Z-Score
11   50  3.037793

# Remove the outliers

In [12]:
df = df[df['Z-Score'] <= 3]

# Print Data without outliers

In [13]:
print(f"Here is the data without outliers: \n {df}")

Here is the data without outliers:
     Age   Z-Score
0    20 -0.938954
1    21 -0.806396
2    22 -0.673838
3    23 -0.541280
4    24 -0.408721
5    25 -0.276163
6    26 -0.143605
7    27 -0.011047
8    28  0.121512
9    29  0.254070
10   30  0.386628